title: My Jekyll Site
description: A cool-looking Jekyll site hosted on GitHub Pages.
baseurl: ""
url: "https://yourusername.github.io"
theme: minima

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass Configuration
sass:
  style: compressed
